# Generated by Django 4.1.2 on 2023-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='mac_address',
            field=models.CharField(max_length=100),
        ),
    ]
